# Generated by Django 4.2.4 on 2023-09-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
